name: 브랜치 관리

on:
  push:
    branches:
      - '*'
      - '!dev'
      - '!main'
  pull_request:
    branches:
      - '*'
      - '!dev'

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if branch is allowed
        run: |
          if [[ ${{ github.event_name }} == 'push' && (${{ github.ref }} == 'refs/heads/dev' || ${{ github.ref }} == 'refs/heads/main') ]]; then
            echo "Branch is allowed.";
          elif [[ ${{ github.event_name }} == 'pull_request' && (${{ github.event.action }} == 'opened' || ${{ github.event.action }} == 'synchronize') ]]; then
            if [[ ${{ github.head_ref }} == 'dev' || ${{ github.head_ref }} == 'main' ]]; then
              echo "Branch is allowed.";
            else
              echo "Branch is not allowed.";
              exit 1;
            fi
          else
            echo "Branch is not allowed.";
            exit 1;
          fi
